services:
  tg_ai_news_app:
    build: .
    image: tg_ai_news_app
    container_name: tg_ai_news_app
    restart: always
#    command: "python main.py"
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./tmp:./tg_ai_news_dir
